version: '3.7'
name: fyp-grading

services:
  frontend:
    build:
      context: ../frontend
    container_name: frontend
    image: frontend
    ports:
      - '80:80'
    networks:
      - fyp-grading

  admin-service:
    build:
      context: ../backend/admin-service
    container_name: admin-service
    image: admin-service
    ports:
      - '8080:8081'
    networks:
      - fyp-grading

  evaluation-service:
    build:
      context: ../backend/evaluation-service
    container_name: evaluation-service
    image: evaluation-service
    ports:
      - '8080:8082'
    networks:
      - fyp-grading

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - fyp-grading

  postgres-admin:
    image: postgres:latest
    container_name: postgres-admin
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: admin-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
        - fyp-grading

  postgres-rubric:
    image: postgres:latest
    container_name: postgres-rubric
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: rubric-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - fyp-grading

  postgres-notification:
    image: postgres:latest
    container_name: postgres-notification
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - fyp-grading

  mongodb:
    image: mongodb:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: evaluation-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
        - fyp-grading

networks:
  fyp-grading:
    driver: bridge