version: '3.7'
name: fyp-grading

services:
  frontend:
    build:
      context: ../frontend/fyp-grading-frontend
    container_name: frontend
    image: frontend
    ports:
      - '80:80'
    networks:
      - fyp-grading

  eureka-registry:
    build:
      context: ../cloud/EurekaService
    image: eureka-service
    ports:
      - '8761:8761'
    networks:
      - fyp-grading

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - fyp-grading
    environment:
      - spring.data.redis.host=redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - fyp-grading

  postgres-admin:
    image: postgres:latest
    container_name: postgres-admin
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: admin-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - fyp-grading

  postgres-rubric:
    image: postgres:latest
    container_name: postgres-rubric
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: rubric-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - fyp-grading

  postgres-notification:
    image: postgres:latest
    container_name: postgres-notification
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - fyp-grading

  mongodb:
    image: mongodb:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: evaluation-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - fyp-grading

  api-gateway:
    build:
      context: ../cloud/api-gateway
    image: api-gateway
    ports:
      - '9191:9191'
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka/
      - spring.data.redis.host=redis
    networks:
      - fyp-grading
    deploy:
      replicas: 1
    depends_on:
      - redis
      - eureka-registry

  admin-service:
    build:
      context: ../backend/fyp-grading-admin-service
    image: admin-service
    networks:
      - fyp-grading
    deploy:
      replicas: 2
    environment:
      - spring.datasource.url= jdbc:postgresql://postgres-admin:5432/admin-db
      - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka/
      - spring.rabbitmq.host=rabbitmq
      - spring.data.redis.host=redis
    depends_on:
      - rabbitmq
      - redis
      - postgres-admin
      - eureka-registry

  evaluation-service:
    build:
      context: ../backend/fyp-grading-evaluation-service
    image: evaluation-service
    networks:
      - fyp-grading
    deploy:
      replicas: 2
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka/
      - spring.data.redis.host=redis
      - spring.data.mongodb.uri=mongodb://admin:admin@mongodb:27017/evaluation-db?authSource=admin&authMechanism=SCRAM-SHA-1
    depends_on:
      - mongodb
      - redis
      - eureka-registry

  notification-service:
    build:
      context: ../backend/fyp-grading-notification-service
    image: notification-service
    networks:
      - fyp-grading
    deploy:
      replicas: 1
    environment:
      - spring.datasource.url= jdbc:postgresql://postgres-notification:5432/notification-db
      - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka/
      - spring.rabbitmq.host=rabbitmq
      - spring.data.redis.host=redis
    depends_on:
      - rabbitmq
      - redis
      - postgres-notification
      - eureka-registry

  rubric-service:
    build:
      context: ../backend/fyp-grading-rubric-service
    image: rubric-service
    networks:
      - fyp-grading
    deploy:
        replicas: 1
    environment:
        - spring.datasource.url= jdbc:postgresql://postgres-rubric:5432/rubric-db
        - eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka/
        - spring.data.redis.host=redis
    depends_on:
        - postgres-rubric
        - redis
        - eureka-registry

networks:
  fyp-grading:
    driver: bridge