version: '3.7'
name: fyp-grading

# TODO: ADD VOLUMES TO APPROPRIATE SERVICES
services:
  api-gateway:
    build:
      context: ../fyp-grading-api-gateway
    image: ${API_GATEWAY_NAME}:1.0
    container_name: ${API_GATEWAY_NAME}
    environment:
      - SPRING_APPLICATION_NAME=${API_GATEWAY_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BUILD_VERSION=1.0
      - PORT=9191
    ports:
      - '9191:9191'
    expose:
      - 9191
    depends_on:
      redis:
        condition: service_healthy
      admin-service:
        condition: service_healthy
      evaluation-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      rubric-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:9191/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    expose:
      - 6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    extends:
      file: common.yml
      service: network-service

  registry-server:
    build:
      context: ../fyp-grading-registry-server
    image: ${REGISTRY_SERVER_NAME}:1.0
    container_name: ${REGISTRY_SERVER_NAME}
    environment:
      - SPRING_APPLICATION_NAME=${REGISTRY_SERVER_NAME}
      - BUILD_VERSION=1.0
      - PORT=8761
    ports:
      - '8761:8761'
    expose:
      - 8761
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  config-server:
    build:
      context: ../fyp-grading-config-server
    image: ${CONFIG_SERVER_NAME}:1.0
    container_name: ${CONFIG_SERVER_NAME}
    environment:
      - GIT_REPO_URI=https://github.com/FirasKhalife/fyp-grading-config.git
      - GIT_BRANCH=cloud-course
      - SPRING_PROFILES_ACTIVE=git,prod
      - SPRING_APPLICATION_NAME=${CONFIG_SERVER_NAME}
      - BUILD_VERSION=1.0
      - PORT=8071
    ports:
      - '8071:8071'
    expose:
      - 8071
    depends_on:
      rabbitmq:
        condition: service_healthy
      registry-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"]
    extends:
      file: common.yml
      service: spring-service

  rabbitmq:
    image: rabbitmq:4.0-rc-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - 5672
      - 15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common.yml
      service: network-service

  frontend:
    build:
      context: ../fyp-grading-frontend
    image: ${FRONTEND_SERVICE_NAME}:1.0
    container_name: ${FRONTEND_SERVICE_NAME}
    ports:
      - '80:80'
    expose:
      - 80
    extends:
      file: common.yml
      service: network-service

  admin-service:
    build:
      context: ../fyp-grading-admin-service
    image: ${ADMIN_SERVICE_NAME}:1.0
    container_name: ${ADMIN_SERVICE_NAME}
    environment:
      - DATABASE_URL=jdbc:postgresql://admin-db:5432/admin-db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - EVALUATION_SERVICE_NAME=${EVALUATION_SERVICE_NAME}
      - NOTIFICATION_SERVICE_NAME=${NOTIFICATION_SERVICE_NAME}
      - SPRING_APPLICATION_NAME=${ADMIN_SERVICE_NAME}
      - BUILD_VERSION=1.0
      - PORT=8080
    expose:
      - 8080
    depends_on:
      config-server:
        condition: service_healthy
      admin-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  admin-db:
    image: postgres:latest
    container_name: admin-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: admin-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    extends:
      file: common.yml
      service: postgres-service

  evaluation-service:
    build:
      context: ../fyp-grading-evaluation-service
    image: ${EVALUATION_SERVICE_NAME}:1.0
    container_name: ${EVALUATION_SERVICE_NAME}
    environment:
      - DATABASE_URL=mongodb://admin:admin@mongodb:27017/evaluation-db?authSource=admin&authMechanism=SCRAM-SHA-1
      - ADMIN_SERVICE_NAME=${ADMIN_SERVICE_NAME}
      - RUBRIC_SERVICE_NAME=${RUBRIC_SERVICE_NAME}
      - SPRING_APPLICATION_NAME=${EVALUATION_SERVICE_NAME}
      - BUILD_VERSION=1.0
      - PORT=8080
    expose:
      - 8080
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: evaluation-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    expose:
      - 27017
    extends:
      file: common.yml
      service: network-service

  notification-service:
    build:
      context: ../fyp-grading-notification-service
    image: ${NOTIFICATION_SERVICE_NAME}:1.0
    container_name: ${NOTIFICATION_SERVICE_NAME}
    environment:
      - DATABASE_URL=jdbc:postgresql://notification-db:5432/notification-db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - SPRING_APPLICATION_NAME=${NOTIFICATION_SERVICE_NAME}
      - BUILD_VERSION=1.0
      - PORT=8080
    expose:
      - 8080
    depends_on:
      config-server:
        condition: service_healthy
      notification-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  notification-db:
    image: postgres:latest
    container_name: notification-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    extends:
      file: common.yml
      service: postgres-service

  rubric-service:
    build:
      context: ../fyp-grading-rubric-service
    image: ${RUBRIC_SERVICE_NAME}:1.0
    container_name: ${RUBRIC_SERVICE_NAME}
    environment:
      - DATABASE_URL=jdbc:postgresql://rubric-db:5432/rubric-db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - SPRING_APPLICATION_NAME=${RUBRIC_SERVICE_NAME}
      - BUILD_VERSION=1.0
      - PORT=8080
    expose:
      - 8080
    depends_on:
      config-server:
        condition: service_healthy
      rubric-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  rubric-db:
    image: postgres:latest
    container_name: rubric-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: rubric-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    extends:
      file: common.yml
      service: postgres-service

networks:
  fyp-grading:
    driver: bridge
