version: '3.7'
name: ${PROJECT_NAME}

services:
  registry-server:
    build:
      context: ../../fyp-grading-registry-server
    image: ${REGISTRY_SERVER_NAME}:1.0
    container_name: ${REGISTRY_SERVER_NAME}
    environment:
      - SPRING_APPLICATION_NAME=${REGISTRY_SERVER_NAME}
      - BUILD_VERSION=1.0
      - PORT=8761
    ports:
      - '8761:8761'
    expose:
      - 8761
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  config-server:
    build:
      context: ../../fyp-grading-config-server
    image: ${CONFIG_SERVER_NAME}:1.0
    container_name: ${CONFIG_SERVER_NAME}
    environment:
      - GIT_REPO_URI=${GIT_REPO_URI}
      - GIT_BRANCH=${GIT_BRANCH}
      - SPRING_APPLICATION_NAME=${CONFIG_SERVER_NAME}
      - SPRING_PROFILES_ACTIVE=git,prod
      - BUILD_VERSION=1.0
      - PORT=8071
    ports:
      - '8071:8071'
    expose:
      - 8071
    depends_on:
      rabbitmq:
        condition: service_healthy
      registry-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

  api-gateway:
    build:
      context: ../../fyp-grading-api-gateway
    image: ${API_GATEWAY_NAME}:1.0
    container_name: ${API_GATEWAY_NAME}
    environment:
      - AUTH_SERVER_URL=http://keycloak-server:8080/realms/master
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTH_SERVER_URL=http://localhost:7080/realms/master
      - ALLOWED_ORIGINS=http://localhost:[*]
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ALLOWED_HEADERS=Authorization,Content-Type
      - SPRING_APPLICATION_NAME=${API_GATEWAY_NAME}
      - BUILD_VERSION=1.0
      - PORT=9191
    ports:
      - '9191:9191'
    expose:
      - 9191
    depends_on:
      keycloak-server:
        condition: service_healthy
      redis:
        condition: service_healthy
      admin-service:
        condition: service_healthy
      evaluation-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      rubric-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:9191/actuator/health/readiness | grep UP || exit 1" ]
    extends:
      file: common.yml
      service: spring-service

networks:
  fyp-grading:
    name: ${GLOBAL_NETWORK_NAME}
