version: '3.7'
name: ${PROJECT_NAME}

# TODO: ADD VOLUMES
services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    expose:
      - 6379
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    extends:
      file: common.yml
      service: network-service

networks:
  fyp-grading:
    name: ${GLOBAL_NETWORK_NAME}
